name: Test cache

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.set_version.outputs.ver }}
    steps:
      - name: Set ver
        id: set_version
        run: |
          echo ::set-output name=ver::"v2.0.2"
  
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/zephyrproject-rtos/ci:v0.23.3
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.14.2
      CLANG_ROOT_DIR: /usr/lib/llvm-12
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      board-name: nrf52840dk_nrf52840
    strategy:
        matrix:
          board-name: [nrf52840dk_nrf52840, nrf52dk_nrf52832]
    steps:
      - run: |
          mkdir app && cd app
          west init -m https://github.com/nrfconnect/sdk-nrf --mr ${{needs.config.outputs.ver}}
          west update
          pip3 install --user -r zephyr/scripts/requirements.txt
          pip3 install --user -r nrf/scripts/requirements.txt
          pip3 install --user -r bootloader/mcuboot/scripts/requirements.txt
          pip3 install ecdsa
      - name: Build sample
        working-directory: app
        run: |
            ls
            cd nrf/samples/bluetooth/mesh/chat
            west build -b ${{ matrix.board-name }}
      - name: Cache build
        uses: actions/cache@v2
        id: cache-build
        with:
          path: nrf/samples/bluetooth/mesh/chat/build
          key: buildfw-${{ github.sha }}-${{ matrix.board-name }}
          restore-keys: |
            buildfw-${{ github.sha }}
      - name: Status 
        run: |
          FILESIZE=$(wc -c < nrf/samples/bluetooth/mesh/chat/build/zephyr/zephyr.bin)
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -d '{"state":"success","target_url":"https://example.com/build/status","description":"Firmware >> $FILESIZE","context":"robot/${{ matrix.board-name }}"}'
  store:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore build
        uses: actions/cache@v2
        id: cache-build
        with:
          path: builds
          key: buildfw-${{ github.sha }}
          
